# Generated by Django 3.0.2 on 2020-04-24 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(default=None, max_length=500, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('content_type', models.CharField(default=None, max_length=50, null=True)),
                ('level', models.CharField(default=None, max_length=10, null=True)),
                ('updated_time', models.DateTimeField(default=None, null=True)),
                ('role', models.CharField(default=None, max_length=50, null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('status_txt', models.CharField(default='live', max_length=100)),
                ('check_role', models.BooleanField(default=False, null=True)),
                ('ready', models.BooleanField(default=False, null=True)),
                ('counter', models.IntegerField(default=30, null=True)),
                ('voted_time', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('difficulty', models.CharField(max_length=10)),
                ('numOfPlayers', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
                ('pictureURL', models.URLField()),
                ('begin_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('comment_board', models.CharField(default="Please Check Your role.\nAnd Don't tell others.\nIf you are ready, Click the Ready button.\n", max_length=2000)),
                ('wolf_kill_number', models.IntegerField(default=0)),
                ('game_log', models.CharField(default='start', max_length=100)),
                ('seer_select', models.BooleanField(default=False, null=True)),
                ('doctor_heal_or_not', models.BooleanField(default=False, null=True)),
                ('voted_user_number', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('doctor_heal', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_heal', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(default=None, related_name='players', to=settings.AUTH_USER_MODEL)),
                ('seer_select_player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seer_select_player', to=settings.AUTH_USER_MODEL)),
                ('voted_users', models.ManyToManyField(default=None, related_name='voted_users', to=settings.AUTH_USER_MODEL)),
                ('wolf_kill_1', models.ManyToManyField(default=None, related_name='wolf_kill_1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audioURL', models.CharField(default=None, max_length=500, null=True)),
                ('belong_room', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='werewolf.Room')),
                ('belong_to', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='werewolf.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='currentRoom',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='werewolf.Room'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
